version: '3'
services:
  my_r_script:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - ./datasets:/usr/src/app/datasets
      - ./inputs:/usr/src/app/inputs
      - ./outputs:/usr/src/app/outputs